(function(){
  const AUDIO_API='https://discoveryprovider.audius.co/v1'; let musicAudio=null;
  function boot(){
    const panels=[...document.querySelectorAll('main.page > section')],hero=document.querySelector('.hero'),birth=hero?.nextElementSibling;
    const history=panels.find(x=>x.querySelector('#historyCard')),sky=panels.find(x=>x.querySelector('#skyCard')),famous=panels.find(x=>x.querySelector('#famousList')),search=panels.find(x=>x.querySelector('#searchBox')),compare=panels.find(x=>x.querySelector('#compareResult')),sound=panels.find(x=>x.querySelector('#soundBtn'));
    if(!birth)return; panels.forEach(x=>x.classList.add('app-view')); if(hero)hero.classList.add('app-view','active','home-hero'); birth.classList.add('app-view','active','home-panel'); [history,sky,famous,search,compare,sound].forEach(x=>x&&x.classList.add('app-view'));
    const quickNav=()=>document.getElementById('quickNav');
    const nav=document.createElement('nav');nav.className='app-bottom-tabs';nav.setAttribute('aria-label','ناوبری اصلی');nav.innerHTML=[['home','⌂','خانه'],['history','📜','تاریخ'],['sky','🔭','آسمان'],['famous','👤','چهره‌ها'],['more','☷','بیشتر']].map(t=>`<button class="app-tab ${t[0]==='home'?'active':''}" data-tab="${t[0]}"><span class="app-tab-icon">${t[1]}</span><span class="app-tab-label">${t[2]}</span></button>`).join('');document.body.appendChild(nav);
    const theme=document.querySelector('#themeBtn');if(theme&&sound){const host=sound.querySelector('.tool-panel')||sound,t=document.createElement('button');t.className='theme-menu-btn';t.type='button';t.innerHTML='🌙 <span>حالت شب</span>';t.onclick=()=>window.toggleTheme?.();host.insertBefore(t,host.firstChild)}
    function activate(tab){let targets=tab==='home'?[birth]:tab==='history'?[history]:tab==='sky'?[sky]:tab==='famous'?[famous]:[search,compare,sound];document.body.classList.add('page-transition');setTimeout(()=>{panels.forEach(x=>x.classList.remove('active'));if(hero)hero.classList.remove('active');birth.classList.remove('active');const q=quickNav();if(q)q.classList.remove('active');document.querySelectorAll('.app-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));if(tab==='home'){if(hero)hero.classList.add('active');birth.classList.add('active')}targets.filter(Boolean).forEach(x=>x.classList.add('active'));if(tab==='home'&&q)q.classList.add('active');window.scrollTo({top:0,behavior:'auto'})},150);setTimeout(()=>document.body.classList.remove('page-transition'),650)}
    nav.addEventListener('click',e=>{const b=e.target.closest('.app-tab');if(b){spawnParticles(b,e);activate(b.dataset.tab)}});setupMusic();
  }
  function spawnParticles(btn,e){const r=btn.getBoundingClientRect(),x=e.clientX||r.left+r.width/2,y=e.clientY||r.top+r.height/2;for(let i=0;i<14;i++){const p=document.createElement('i');p.className='tap-particle';p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--dx',((Math.random()-.5)*100)+'px');p.style.setProperty('--dy',((Math.random()-.5)*90-25)+'px');p.style.setProperty('--delay',(Math.random()*.12)+'s');document.body.appendChild(p);setTimeout(()=>p.remove(),800)}}
  async function setupMusic(){const old=document.getElementById('soundBtn'),host=old?.parentElement;if(!host)return;const player=document.createElement('div');player.className='ambient-player';player.innerHTML=`<button class="ambient-toggle" id="ambientToggle" aria-label="پخش موسیقی">▶</button><div class="ambient-info"><b>موسیقی آرام</b><span id="ambientStatus">در حال آماده‌سازی…</span></div><div class="ambient-wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><button class="ambient-mute" id="ambientMute" aria-label="قطع صدا">🔊</button>`;host.insertBefore(player,old);old.style.display='none';const toggle=document.getElementById('ambientToggle'),mute=document.getElementById('ambientMute'),status=document.getElementById('ambientStatus');try{const r=await fetch(`${AUDIO_API}/tracks/search?query=ambient%20calm&limit=8`),j=await r.json(),tracks=(j.data||[]).filter(t=>t.duration>=60&&t.duration<=420&&t.streamable!==false),track=tracks[0];if(!track)throw 0;musicAudio=new Audio(`${AUDIO_API}/tracks/${track.id}/stream`);musicAudio.loop=true;musicAudio.preload='none';musicAudio.volume=.16;status.textContent=`${track.title||'Ambient'} • موسیقی پس‌زمینه`;toggle.onclick=async()=>{if(musicAudio.paused){try{await musicAudio.play();toggle.textContent='❚❚';player.classList.add('playing')}catch(e){status.textContent='برای پخش، یک‌بار روی دکمه بزن'}}else{musicAudio.pause();toggle.textContent='▶';player.classList.remove('playing')}};mute.onclick=()=>{musicAudio.muted=!musicAudio.muted;mute.textContent=musicAudio.muted?'🔇':'🔊'}}catch(e){status.textContent='موسیقی آنلاین در دسترس نیست';toggle.disabled=true;toggle.textContent='—'}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();