const months=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const monthDays=[31,31,31,31,31,31,30,30,30,30,30,29];
const traits=['خلاقیت','اعتمادبه‌نفس','شادی','تعادل','آرامش','عزم','قدرت','شهود','جذابیت','جسارت','اصالت','امید','طراوت','وفاداری','ماجراجویی'];
const specialDates={'7-10':{color:'#00FFFF',colorName:'Cyan',trait:'قدرت',description:'انرژی بالا، حضور پررنگ و توانایی تأثیرگذاری از ویژگی‌های این روز است.'},'11-30':{color:'#FFD700',colorName:'زرد طلایی',trait:'اصالت',description:'ذهنی مستقل، شخصیت متفاوت و تمایل به ساختن مسیر مخصوص خودت از ویژگی‌های این روز است.'},'5-22':{color:'#90EE90',colorName:'سبز روشن',trait:'طراوت',description:'انرژی تازه، حس رشد و روحیه‌ای روشن و امیدوار از ویژگی‌های این روز است.'}};
const colorNames=['قرمز مرجانی','نارنجی آفتابی','زرد لیمویی','سبز بهاری','فیروزه‌ای','آبی آسمانی','نیلی','بنفش رویایی','صورتی شکوفه‌ای','سرخابی','طلایی گرم','سبز زمردی','آبی اقیانوسی','یاسی','هلویی'];
const faDigits=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const monthSelect=document.getElementById('month'),daySelect=document.getElementById('day'),result=document.getElementById('result'),toast=document.getElementById('toast');
function hashDate(m,d){let n=0;for(let i=1;i<m;i++)n+=monthDays[i-1];return n+d-1}
function hslToHex(h,s,l){s/=100;l/=100;const k=n=>(n+h/30)%12,a=s*Math.min(l,1-l),f=n=>l-a*Math.max(-1,Math.min(k(n)-3,Math.min(9-k(n),1)));return '#'+[f(0),f(8),f(4)].map(x=>Math.round(255*x).toString(16).padStart(2,'0')).join('').toUpperCase()}
function getData(m,d){const key=`${m}-${d}`;if(specialDates[key])return {...specialDates[key],m,d,index:hashDate(m,d)};const i=hashDate(m,d),hue=(i*47+13)%360,color=hslToHex(hue,78,61),trait=traits[(i*7+m+d)%traits.length],colorName=colorNames[i%colorNames.length],descriptions=[`ترکیبی از انرژی ${trait}، نگاه مثبت و حضور خاص تو، امضای این روز را می‌سازد.`,`آرامش درونی، خلاقیت و میل به رشد از انرژی‌های پررنگ این روز هستند.`,`این روز نماد شخصیتی مستقل، پرانرژی و متفاوت است که مسیر خودش را پیدا می‌کند.`];return{m,d,index:i,color,colorName,trait,description:descriptions[i%descriptions.length]}}
function allDates(){const a=[];for(let m=1;m<=12;m++)for(let d=1;d<=monthDays[m-1];d++)a.push(getData(m,d));return a}const all=allDates();
function fillMonth(sel,withPlaceholder=true){sel.innerHTML=withPlaceholder?'<option value="">ماه را انتخاب کن</option>':'';months.forEach((name,i)=>{const o=document.createElement('option');o.value=i+1;o.textContent=name;sel.appendChild(o)})}
function fillDaysFor(sel,m,withPlaceholder=true){sel.innerHTML=withPlaceholder?'<option value="">روز را انتخاب کن</option>':'';if(!m)return;for(let d=1;d<=monthDays[m-1];d++){const o=document.createElement('option');o.value=d;o.textContent=faDigits(d);sel.appendChild(o)}}
fillMonth(monthSelect);daySelect.disabled=true;monthSelect.addEventListener('change',()=>{fillDaysFor(daySelect,Number(monthSelect.value));daySelect.disabled=!monthSelect.value;result.style.display='none'});daySelect.addEventListener('change',()=>result.style.display='none');

// تبدیل جلالی به میلادی؛ سال فقط برای داده‌های نجومی امسال استفاده می‌شود و از کاربر پرسیده نمی‌شود.
function jalaliToGregorian(jy,jm,jd){const epbase=jy-(jy>=0?474:473),epyear=474+(epbase%2820),mdays=jm<=7?(jm-1)*31:(jm-1)*30+6;let days=jd+mdays+Math.floor((epyear*682-110)/2816)+(epyear-1)*365+Math.floor(epbase/2820)*1029983+(1948320-1);let jdn=days;let l=jdn+68569,n=Math.floor(4*l/146097);l-=Math.floor((146097*n+3)/4);let y=Math.floor(4000*(l+1)/1461001);l-=Math.floor(1461*y/4)+31;let m=Math.floor(80*l/2447);let d=l-Math.floor(2447*m/80);l=Math.floor(m/11);m=m+2-12*l;y=100*(n-49)+y+l;return[y,m,d]}
function currentPersianYear(){const now=new Date();const gy=now.getFullYear(),gm=now.getMonth()+1,gd=now.getDate();return gm>3||gm===3&&gd>=21?gy-621:gy-622}
function gregorianForDate(m,d){return jalaliToGregorian(currentPersianYear(),m,d)}
function moonInfo(date){const synodic=29.530588853,known=new Date(Date.UTC(2000,0,6,18,14)),days=(date-known)/86400000,age=((days%synodic)+synodic)%synodic,illum=(1-Math.cos(2*Math.PI*age/synodic))/2;let phase='ماه نو';if(age<1.85)phase='ماه نو';else if(age<7.38)phase='هلال افزاینده';else if(age<9.23)phase='تربیع اول';else if(age<14.77)phase='کوژ افزاینده';else if(age<16.61)phase='ماه کامل';else if(age<22.15)phase='کوژ کاهنده';else if(age<23.99)phase='تربیع آخر';else phase='هلال کاهنده';return{age,illum,phase}}
function moonEmoji(age){return age<1.85?'🌑':age<7.38?'🌒':age<9.23?'🌓':age<14.77?'🌔':age<16.61?'🌕':age<22.15?'🌖':age<23.99?'🌗':'🌘'}

const famousByGregorian={'08-13':[
 {name:'آندرس یونس آنگستروم',year:1814,field:'فیزیک و اخترشناسی',note:'پژوهشگر طیف‌سنجی؛ واحد آنگستروم به نام اوست.'},
 {name:'ریچارد ویلشتتر',year:1872,field:'شیمی',note:'برنده نوبل شیمی ۱۹۱۵.'},
 {name:'سالوادور لوریا',year:1912,field:'میکروب‌شناسی',note:'برنده نوبل فیزیولوژی یا پزشکی ۱۹۶۹.'},
 {name:'فردریک سنگر',year:1918,field:'بیوشیمی',note:'تنها فردی که دو بار نوبل شیمی دریافت کرده است.'},
 {name:'جان لوگی برد',year:1888,field:'مهندسی',note:'از پیشگامان توسعه تلویزیون.'},
 {name:'آلفرد هیچکاک',year:1899,field:'سینما',note:'از اثرگذارترین کارگردانان تاریخ سینما.'},
 {name:'لوسی استون',year:1818,field:'حقوق زنان و آموزش',note:'از چهره‌های مهم جنبش حقوق زنان در آمریکا.'}
], '01-04':[{name:'ایزاک نیوتن',year:1643,field:'فیزیک و ریاضیات',note:'از بنیان‌گذاران فیزیک کلاسیک.'}], '03-14':[{name:'آلبرت اینشتین',year:1879,field:'فیزیک',note:'نظریه نسبیت و برنده نوبل فیزیک.'}], '12-25':[{name:'آیزاک نیوتن',year:1642,field:'فیزیک و ریاضیات',note:'در تقویم ژولینی؛ تاریخ میلادی مدرن او ۴ ژانویه ثبت می‌شود.'}]};
function renderSkyAndFamous(m,d){const [gy,gm,gd]=gregorianForDate(m,d),date=new Date(Date.UTC(gy,gm-1,gd,12)),moon=moonInfo(date),pct=Math.round(moon.illum*100),key=`${String(gm).padStart(2,'0')}-${String(gd).padStart(2,'0')}`,people=famousByGregorian[key]||[];document.getElementById('skyCard').innerHTML=`<div class="moon-visual"><div class="moon" style="--moon:${pct}%">${moonEmoji(moon.age)}</div><div><b>${moon.phase}</b><span>${faDigits(pct)}٪ روشنایی ماه</span><small>معادل میلادی امسال: ${faDigits(gd)} ${['ژانویه','فوریه','مارس','آوریل','مه','ژوئن','ژوئیه','اوت','سپتامبر','اکتبر','نوامبر','دسامبر'][gm-1]} ${faDigits(gy)}</small></div></div><div class="stars-field" aria-label="آسمان ستاره‌ای"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><b>✦ آسمان شب ✦</b></div><div class="science-note">فاز ماه با چرخهٔ سینودیک محاسبه شده است. برای نقشهٔ واقعی ستاره‌ها، ساعت دقیق تولد و مختصات محل لازم است؛ بنابراین این بخش عمداً ادعای «نقشهٔ دقیق آسمان» نمی‌کند.</div>`;document.getElementById('famousList').innerHTML=people.length?people.map(p=>`<div class="famous"><div class="famous-year">${faDigits(p.year)}</div><div><strong>${p.name}</strong><span>${p.field}</span><small>${p.note}</small></div></div>`).join(''):`<div class="empty">برای این تاریخ در فهرست فعلی چهرهٔ شاخص ثبت نشده است؛ می‌توانیم بانک مشاهیر را بزرگ‌تر کنیم.</div>`}

function showResult(m=Number(monthSelect.value),d=Number(daySelect.value),scroll=true){if(!m){showToast('اول ماه تولدت رو انتخاب کن ✨');monthSelect.focus();return}if(!d){showToast('حالا روز تولدت رو انتخاب کن ✨');daySelect.focus();return}const x=getData(m,d);document.documentElement.style.setProperty('--result-color',x.color);document.documentElement.style.setProperty('--result-glow',x.color+'44');const orb=document.getElementById('orb');orb.style.background=x.color;orb.style.boxShadow=`0 20px 60px ${x.color},inset -18px -18px 35px #0002,inset 12px 12px 25px #fff8`;document.getElementById('date').textContent=`${faDigits(d)} ${months[m-1]}`;document.getElementById('color').textContent=x.colorName;document.getElementById('hex').textContent=x.color;document.getElementById('trait').textContent=`✦ ${x.trait} ✦`;document.getElementById('desc').textContent=x.description;document.getElementById('stats').innerHTML=`<div class="stat"><b>📅 روز سال</b><span>${faDigits(x.index+1)} از ${faDigits(all.length)}</span></div><div class="stat"><b>🎨 HEX</b><span>${x.color}</span></div><div class="stat"><b>📊 شاخص رنگ</b><span>${faDigits((x.index%100)+1)}</span></div><div class="stat"><b>🧪 مبنا</b><span>HSL</span></div>`;renderSkyAndFamous(m,d);result.style.display='block';if(scroll)result.scrollIntoView({behavior:'smooth',block:'nearest'});playTone(x.color)}
function randomDate(){const x=all[Math.floor(Math.random()*all.length)];monthSelect.value=x.m;fillDaysFor(daySelect,x.m);daySelect.disabled=false;daySelect.value=x.d;showResult(x.m,x.d)}
function setupCompare(){[document.getElementById('cm1'),document.getElementById('cm2')].forEach(fillMonth);[1,2].forEach(n=>{const m=document.getElementById('cm'+n),d=document.getElementById('cd'+n);d.innerHTML='<option value="">روز</option>';m.addEventListener('change',()=>fillDaysFor(d,Number(m.value),true))})}setupCompare();
function compareDates(){const m1=Number(document.getElementById('cm1').value),d1=Number(document.getElementById('cd1').value),m2=Number(document.getElementById('cm2').value),d2=Number(document.getElementById('cd2').value);if(!m1||!d1||!m2||!d2){showToast('هر دو تاریخ را کامل انتخاب کن 💞');return}const a=getData(m1,d1),b=getData(m2,d2),compat=Math.max(62,100-Math.abs(a.index-b.index)%39);document.getElementById('compareResult').innerHTML=`<div class="compare-result"><div class="compare-colors"><div><div class="compare-ball" style="background:${a.color}"></div><b>${months[m1-1]} ${faDigits(d1)}</b><small>${a.trait}</small></div><div><div class="compare-ball" style="background:${b.color}"></div><b>${months[m2-1]} ${faDigits(d2)}</b><small>${b.trait}</small></div></div><div class="compat">${faDigits(compat)}٪ هماهنگی</div><p>این درصد یک شاخص سرگرم‌کننده بر پایه فاصلهٔ تقویمی/رنگی است، نه یک معیار علمی شخصیت‌شناسی.</p></div>`}
function searchColors(){const q=document.getElementById('searchBox').value.trim().toLowerCase(),box=document.getElementById('searchResults');if(!q){box.innerHTML='';return}const hits=all.filter(x=>x.colorName.toLowerCase().includes(q)||x.trait.toLowerCase().includes(q)||x.color.toLowerCase().includes(q)).slice(0,12);box.innerHTML=hits.length?hits.map(x=>`<button class="search-card" onclick="selectSearch(${x.m},${x.d})"><i class="swatch" style="background:${x.color}"></i><span><strong>${x.colorName}</strong><small>${faDigits(x.d)} ${months[x.m-1]} · ${x.trait}</small></span></button>`).join(''):'<div>نتیجه‌ای پیدا نشد ✨</div>'}
function selectSearch(m,d){monthSelect.value=m;fillDaysFor(daySelect,m);daySelect.disabled=false;daySelect.value=d;showResult(m,d)}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('birthday-dark',document.body.classList.contains('dark'));document.getElementById('themeBtn').textContent=document.body.classList.contains('dark')?'☀️':'🌙'}
if(localStorage.getItem('birthday-dark')==='true'){document.body.classList.add('dark');document.getElementById('themeBtn').textContent='☀️'}
let soundOn=true,audioCtx;function toggleSound(){soundOn=!soundOn;document.getElementById('soundBtn').textContent=soundOn?'🔊 صدا روشن است':'🔇 صدا خاموش است';if(soundOn)playTone('#7c3aed')}
function playTone(hex){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=440+parseInt(hex.slice(1,3),16);o.type='sine';g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.035,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.22);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.23)}catch(e){}}
async function shareResult(){const text=`راز رنگ تولد من\n${document.getElementById('date').textContent}\nرنگ: ${document.getElementById('color').textContent} ${document.getElementById('hex').textContent}\nویژگی: ${document.getElementById('trait').textContent}`;if(navigator.share){try{await navigator.share({title:'راز رنگ تولد',text})}catch(e){}}else{try{await navigator.clipboard.writeText(text);showToast('نتیجه کپی شد ✨')}catch(e){showToast('اشتراک‌گذاری در این مرورگر در دسترس نیست')}}}
function downloadCard(){const m=Number(monthSelect.value),d=Number(daySelect.value);if(!m||!d){showToast('اول رنگ تولدت را کشف کن ✨');return}const x=getData(m,d),c=document.createElement('canvas');c.width=1200;c.height=1500;const ctx=c.getContext('2d');const grad=ctx.createLinearGradient(0,0,1200,1500);grad.addColorStop(0,x.color);grad.addColorStop(.48,'#ffffff');grad.addColorStop(1,'#eef2ff');ctx.fillStyle=grad;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='rgba(255,255,255,.82)';roundRect(ctx,90,100,1020,1300,55);ctx.fill();ctx.textAlign='center';ctx.fillStyle='#101828';ctx.font='bold 42px sans-serif';ctx.fillText('راز رنگ تولد',600,200);ctx.font='bold 70px sans-serif';ctx.fillText(`${faDigits(d)} ${months[m-1]}`,600,330);ctx.beginPath();ctx.arc(600,570,170,0,Math.PI*2);ctx.fillStyle=x.color;ctx.shadowColor=x.color;ctx.shadowBlur=55;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#101828';ctx.font='bold 64px sans-serif';ctx.fillText(x.colorName,600,850);ctx.font='bold 54px sans-serif';ctx.fillText(`✦ ${x.trait} ✦`,600,950);ctx.font='bold 30px monospace';ctx.fillText(x.color,600,1015);ctx.font='30px sans-serif';ctx.fillText(`روز سال: ${x.index+1}  ·  شاخص رنگ: ${(x.index%100)+1}  ·  مبنا: HSL`,600,1100);ctx.font='26px sans-serif';ctx.fillStyle='#667085';wrapText(ctx,x.description,600,1190,800,45);ctx.font='22px sans-serif';ctx.fillText('birthday color experience ✨',600,1330);const a=document.createElement('a');a.download=`birthday-color-${m}-${d}.jpg`;a.href=c.toDataURL('image/jpeg',.94);a.click();showToast('کارت JPG آماده شد 🖼️')}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
function wrapText(ctx,text,x,y,max,lh){const words=text.split(' ');let line='';for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>max){ctx.fillText(line,x,y);line=word+' ';y+=lh}else line=test}ctx.fillText(line,x,y)}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
