const months=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const gregMonths=['ژانویه','فوریه','مارس','آوریل','مه','ژوئن','ژوئیه','اوت','سپتامبر','اکتبر','نوامبر','دسامبر'];
const traits=['خلاقیت','اعتمادبه‌نفس','شادی','تعادل','آرامش','عزم','قدرت','شهود','جذابیت','جسارت','اصالت','امید','طراوت','وفاداری','ماجراجویی'];
const specialDates={'7-10':{color:'#00FFFF',colorName:'Cyan',trait:'قدرت',description:'انرژی بالا، حضور پررنگ و توانایی تأثیرگذاری از ویژگی‌های این روز است.'},'11-30':{color:'#FFD700',colorName:'زرد طلایی',trait:'اصالت',description:'ذهنی مستقل، شخصیت متفاوت و تمایل به ساختن مسیر مخصوص خودت از ویژگی‌های این روز است.'},'5-22':{color:'#90EE90',colorName:'سبز روشن',trait:'طراوت',description:'انرژی تازه، حس رشد و روحیه‌ای روشن و امیدوار از ویژگی‌های این روز است.'}};
const colorNames=['قرمز مرجانی','نارنجی آفتابی','زرد لیمویی','سبز بهاری','فیروزه‌ای','آبی آسمانی','نیلی','بنفش رویایی','صورتی شکوفه‌ای','سرخابی','طلایی گرم','سبز زمردی','آبی اقیانوسی','یاسی','هلویی'];
const faDigits=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const monthSelect=document.getElementById('month'),daySelect=document.getElementById('day'),yearSelect=document.getElementById('year'),result=document.getElementById('result'),toast=document.getElementById('toast');
function currentJalali(){const p=new Intl.DateTimeFormat('en-US-u-ca-persian',{year:'numeric',month:'numeric',day:'numeric'}).formatToParts(new Date());return{y:+p.find(x=>x.type==='year').value,m:+p.find(x=>x.type==='month').value,d:+p.find(x=>x.type==='day').value}}
const nowJ=currentJalali();
function jalaliToGregorian(jy,jm,jd){jy=Number(jy)-979;jm=Number(jm)-1;jd=Number(jd)-1;const md=[31,31,31,31,31,31,30,30,30,30,30,29];let jdn=365*jy+Math.floor(jy/33)*8+Math.floor((jy%33+3)/4);for(let i=0;i<jm;i++)jdn+=md[i];jdn+=jd;let gdn=jdn+79,gy=1600+400*Math.floor(gdn/146097);gdn%=146097;let leap=true;if(gdn>=36525){gdn--;gy+=100*Math.floor(gdn/36524);gdn%=36524;if(gdn>=365)gdn++;else leap=false}gy+=4*Math.floor(gdn/1461);gdn%=1461;if(gdn>=366){leap=false;gdn--;gy+=Math.floor(gdn/365);gdn%=365}const gm=[31,28,31,30,31,30,31,31,30,31,30,31];let i=0;while(gdn>=gm[i]+(i===1&&leap?1:0)){gdn-=gm[i]+(i===1&&leap?1:0);i++}return[gy,i+1,gdn+1]}
function gregDate(y,m,d){const x=jalaliToGregorian(y,m,d);return new Date(Date.UTC(x[0],x[1]-1,x[2],12))}
function isJalaliLeap(y){const a=gregDate(y,1,1),b=gregDate(y+1,1,1);return Math.round((b-a)/86400000)===366}
function daysInMonth(y,m){if(m<=6)return 31;if(m<=11)return 30;return isJalaliLeap(y)?30:29}
function fillYears(){yearSelect.innerHTML='<option value="">سال را انتخاب کن</option>';for(let y=1300;y<=1500;y++){const o=document.createElement('option');o.value=y;o.textContent=faDigits(y);yearSelect.appendChild(o)}yearSelect.value=nowJ.y}
function fillMonth(sel,withPlaceholder=true){sel.innerHTML=withPlaceholder?'<option value="">ماه را انتخاب کن</option>':'';months.forEach((name,i)=>{const o=document.createElement('option');o.value=i+1;o.textContent=name;sel.appendChild(o)})}
function fillDaysFor(sel,m,withPlaceholder=true,y=Number(yearSelect.value)||nowJ.y){sel.innerHTML=withPlaceholder?'<option value="">روز را انتخاب کن</option>':'';if(!m)return;for(let d=1;d<=daysInMonth(y,m);d++){const o=document.createElement('option');o.value=d;o.textContent=faDigits(d);sel.appendChild(o)}}
fillYears();fillMonth(monthSelect);monthSelect.value=nowJ.m;fillDaysFor(daySelect,nowJ.m,true,nowJ.y);daySelect.value=nowJ.d;yearSelect.addEventListener('change',()=>{fillDaysFor(daySelect,Number(monthSelect.value),true,Number(yearSelect.value));result.style.display='none'});monthSelect.addEventListener('change',()=>{fillDaysFor(daySelect,Number(monthSelect.value),true,Number(yearSelect.value)||nowJ.y);daySelect.disabled=!monthSelect.value;result.style.display='none'});daySelect.addEventListener('change',()=>result.style.display='none');
function hashDate(m,d){let n=0;for(let i=1;i<m;i++)n+=i<=6?31:30;return n+d-1}
function hslToHex(h,s,l){s/=100;l/=100;const k=n=>(n+h/30)%12,a=s*Math.min(l,1-l),f=n=>l-a*Math.max(-1,Math.min(k(n)-3,Math.min(9-k(n),1)));return '#'+[f(0),f(8),f(4)].map(x=>Math.round(255*x).toString(16).padStart(2,'0')).join('').toUpperCase()}
function getData(m,d){const key=`${m}-${d}`;if(specialDates[key])return{...specialDates[key],m,d,index:hashDate(m,d)};const i=hashDate(m,d),hue=(i*47+13)%360,color=hslToHex(hue,78,61),trait=traits[(i*7+m+d)%traits.length],colorName=colorNames[i%colorNames.length],descriptions=[`ترکیبی از ویژگی «${trait}» و یک هویت بصری منحصربه‌فرد برای این تاریخ.`,`این رنگ از یک الگوی محاسباتی HSL بر پایه روز تقویمی ساخته شده و تفسیر ویژگی آن جنبه سرگرمی دارد.`,`رنگ این تاریخ یک امضای بصری محاسباتی است؛ ویژگی آن شخصیت‌شناسی علمی محسوب نمی‌شود.`];return{m,d,index:i,color,colorName,trait,description:descriptions[i%descriptions.length]}}
function allDates(){const a=[];for(let m=1;m<=12;m++)for(let d=1;d<=(m<=6?31:m===12?30:30);d++)a.push(getData(m,d));return a}const all=allDates();
const famousByGregorian={'08-13':[{name:'آندرس یونس آنگستروم',year:1814,field:'فیزیک و اخترشناسی',note:'پژوهشگر طیف‌سنجی؛ واحد آنگستروم به نام اوست.'},{name:'ریچارد ویلشتتر',year:1872,field:'شیمی',note:'برنده نوبل شیمی ۱۹۱۵.'},{name:'سالوادور لوریا',year:1912,field:'میکروب‌شناسی',note:'برنده نوبل فیزیولوژی یا پزشکی ۱۹۶۹.'},{name:'فردریک سنگر',year:1918,field:'بیوشیمی',note:'برنده دو جایزه نوبل شیمی.'},{name:'جان لوگی برد',year:1888,field:'مهندسی',note:'از پیشگامان توسعه تلویزیون.'},{name:'آلفرد هیچکاک',year:1899,field:'سینما',note:'از اثرگذارترین کارگردانان تاریخ سینما.'},{name:'لوسی استون',year:1818,field:'حقوق زنان و آموزش',note:'از چهره‌های مهم جنبش حقوق زنان در آمریکا.'}],'01-04':[{name:'ایزاک نیوتن',year:1643,field:'فیزیک و ریاضیات',note:'از بنیان‌گذاران فیزیک کلاسیک.'}],'03-14':[{name:'آلبرت اینشتین',year:1879,field:'فیزیک',note:'نظریه نسبیت و برنده نوبل فیزیک.'}],'12-25':[{name:'آیزاک نیوتن',year:1642,field:'فیزیک و ریاضیات',note:'در تقویم ژولینی؛ تاریخ مدرن میلادی او ۴ ژانویه است.'}]};
function moonInfo(date){const synodic=29.530588853,known=new Date(Date.UTC(2000,0,6,18,14)),days=(date-known)/86400000,age=((days%synodic)+synodic)%synodic,illum=(1-Math.cos(2*Math.PI*age/synodic))/2;let phase='ماه نو';if(age<1.85)phase='ماه نو';else if(age<7.38)phase='هلال افزاینده';else if(age<9.23)phase='تربیع اول';else if(age<14.77)phase='کوژ افزاینده';else if(age<16.61)phase='ماه کامل';else if(age<22.15)phase='کوژ کاهنده';else if(age<23.99)phase='تربیع آخر';else phase='هلال کاهنده';return{age,illum,phase}}
function moonEmoji(age){return age<1.85?'🌑':age<7.38?'🌒':age<9.23?'🌓':age<14.77?'🌔':age<16.61?'🌕':age<22.15?'🌖':age<23.99?'🌗':'🌘'}
function formatGregorian(g){const [y,m,d]=g,date=new Date(Date.UTC(y,m-1,d,12));return{date,text:new Intl.DateTimeFormat('fa-IR-u-ca-gregory',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(date)}}
function ageYears(g){const birth=new Date(Date.UTC(g[0],g[1]-1,g[2])),today=new Date(),now=new Date(Date.UTC(today.getFullYear(),today.getMonth(),today.getDate()));let age=now.getUTCFullYear()-birth.getUTCFullYear();if(now.getUTCMonth()<birth.getUTCMonth()||(now.getUTCMonth()===birth.getUTCMonth()&&now.getUTCDate()<birth.getUTCDate()))age--;return age}
function renderSkyAndFamous(g){const [gy,gm,gd]=g,date=new Date(Date.UTC(gy,gm-1,gd,12)),moon=moonInfo(date),pct=Math.round(moon.illum*100),key=`${String(gm).padStart(2,'0')}-${String(gd).padStart(2,'0')}`,people=famousByGregorian[key]||[],weekday=new Intl.DateTimeFormat('fa-IR-u-ca-gregory',{weekday:'long'}).format(date);document.getElementById('skyCard').innerHTML=`<div class="moon-visual"><div class="moon">${moonEmoji(moon.age)}</div><div><b>${moon.phase}</b><span>${faDigits(pct)}٪ روشنایی ماه</span><small>${faDigits(gy)}/${faDigits(gm)}/${faDigits(gd)} · ${weekday}</small></div></div><div class="stars-field" aria-label="آسمان ستاره‌ای"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><b>✦ آسمان شب ✦</b></div><div class="science-note">فاز ماه با چرخهٔ سینودیک بر اساس تاریخ واقعی تولد محاسبه شده است. برای موقعیت دقیق ستاره‌ها و سیارات، ساعت و مختصات محل تولد هم لازم است.</div>`;document.getElementById('famousList').innerHTML=people.length?people.map(p=>`<div class="famous"><div class="famous-year">${faDigits(p.year)}</div><div><strong>${p.name}</strong><span>${p.field}</span><small>${p.note}</small></div></div>`).join(''):`<div class="empty">برای این روز در بانک فعلی چهرهٔ شاخصی ثبت نشده است.</div>`}
function showResult(m=Number(monthSelect.value),d=Number(daySelect.value),y=Number(yearSelect.value),scroll=true){if(!y){showToast('سال تولدت را انتخاب کن ✨');yearSelect.focus();return}if(!m){showToast('ماه تولدت را انتخاب کن ✨');monthSelect.focus();return}if(!d){showToast('روز تولدت را انتخاب کن ✨');daySelect.focus();return}if(d>daysInMonth(y,m)){showToast('این روز در این سال وجود ندارد ✨');return}const x=getData(m,d),g=jalaliToGregorian(y,m,d),gText=formatGregorian(g),age=ageYears(g),date=new Date(Date.UTC(g[0],g[1]-1,g[2],12)),dayOfYear=Math.floor((date-new Date(Date.UTC(g[0],0,0)))/86400000);document.documentElement.style.setProperty('--result-color',x.color);document.documentElement.style.setProperty('--result-glow',x.color+'44');const orb=document.getElementById('orb');orb.style.background=x.color;orb.style.boxShadow=`0 20px 60px ${x.color},inset -18px -18px 35px #0002,inset 12px 12px 25px #fff8`;document.getElementById('date').textContent=`${faDigits(d)} ${months[m-1]} ${faDigits(y)}`;document.getElementById('gregDate').innerHTML=`معادل میلادی: <strong>${gText.text}</strong>`;document.getElementById('ageLine').innerHTML=age>=0?`<span class="age-badge">🎂 سن فعلی: ${faDigits(age)} سال</span>`:'';document.getElementById('color').textContent=x.colorName;document.getElementById('hex').textContent=x.color;document.getElementById('trait').textContent=`✦ ${x.trait} ✦`;document.getElementById('desc').textContent=x.description;document.getElementById('stats').innerHTML=`<div class="stat"><b>📅 روز سال میلادی</b><span>${faDigits(dayOfYear)}</span></div><div class="stat"><b>🎨 HEX</b><span>${x.color}</span></div><div class="stat"><b>📊 شاخص رنگ</b><span>${faDigits((x.index%100)+1)}</span></div><div class="stat"><b>🧪 مبنا</b><span>HSL</span></div>`;document.getElementById('dateMeta').innerHTML=`<div class="date-meta-card"><b>شمسی</b><span>${faDigits(y)}/${faDigits(m)}/${faDigits(d)}</span></div><div class="date-meta-card"><b>میلادی</b><span>${faDigits(g[0])}/${faDigits(g[1])}/${faDigits(g[2])}</span></div><div class="date-meta-card"><b>روز هفته</b><span>${new Intl.DateTimeFormat('fa-IR-u-ca-gregory',{weekday:'long'}).format(date)}</span></div>`;renderSkyAndFamous(g);result.style.display='block';if(scroll)result.scrollIntoView({behavior:'smooth',block:'nearest'});playTone(x.color)}
function todayDate(){yearSelect.value=nowJ.y;monthSelect.value=nowJ.m;fillDaysFor(daySelect,nowJ.m,true,nowJ.y);daySelect.value=nowJ.d;showResult(nowJ.m,nowJ.d,nowJ.y)}
function randomDate(){const y=1300+Math.floor(Math.random()*201),m=1+Math.floor(Math.random()*12),d=1+Math.floor(Math.random()*daysInMonth(y,m));yearSelect.value=y;monthSelect.value=m;fillDaysFor(daySelect,m,true,y);daySelect.value=d;showResult(m,d,y)}
function setupCompare(){[document.getElementById('cm1'),document.getElementById('cm2')].forEach(fillMonth);[1,2].forEach(n=>{const m=document.getElementById('cm'+n),d=document.getElementById('cd'+n);d.innerHTML='<option value="">روز</option>';m.addEventListener('change',()=>fillDaysFor(d,Number(m.value),true,nowJ.y))})}setupCompare();
function compareDates(){const m1=Number(document.getElementById('cm1').value),d1=Number(document.getElementById('cd1').value),m2=Number(document.getElementById('cm2').value),d2=Number(document.getElementById('cd2').value);if(!m1||!d1||!m2||!d2){showToast('هر دو تاریخ را کامل انتخاب کن 💞');return}const a=getData(m1,d1),b=getData(m2,d2),distance=Math.abs(a.index-b.index),compat=Math.max(62,100-distance%39);document.getElementById('compareResult').innerHTML=`<div class="compare-result"><div class="compare-colors"><div><div class="compare-ball" style="background:${a.color}"></div><b>${months[m1-1]} ${faDigits(d1)}</b><small>${a.trait}</small></div><div><div class="compare-ball" style="background:${b.color}"></div><b>${months[m2-1]} ${faDigits(d2)}</b><small>${b.trait}</small></div></div><div class="compat">${faDigits(compat)}٪</div><p>شاخص تفریحی بر پایه فاصلهٔ تقویمی/رنگی است و معیار علمی سازگاری شخصیت نیست.</p></div>`}
function searchColors(){const q=document.getElementById('searchBox').value.trim().toLowerCase(),box=document.getElementById('searchResults');if(!q){box.innerHTML='';return}const hits=all.filter(x=>x.colorName.toLowerCase().includes(q)||x.trait.toLowerCase().includes(q)||x.color.toLowerCase().includes(q)).slice(0,12);box.innerHTML=hits.length?hits.map(x=>`<button class="search-card" onclick="selectSearch(${x.m},${x.d})"><i class="swatch" style="background:${x.color}"></i><span><strong>${x.colorName}</strong><small>${faDigits(x.d)} ${months[x.m-1]} · ${x.trait}</small></span></button>`).join(''):'<div>نتیجه‌ای پیدا نشد ✨</div>'}
function selectSearch(m,d){monthSelect.value=m;fillDaysFor(daySelect,m,true,Number(yearSelect.value)||nowJ.y);daySelect.disabled=false;daySelect.value=d;showResult(m,d,Number(yearSelect.value)||nowJ.y)}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('birthday-dark',document.body.classList.contains('dark'));document.getElementById('themeBtn').textContent=document.body.classList.contains('dark')?'☀️':'🌙'}
if(localStorage.getItem('birthday-dark')==='true'){document.body.classList.add('dark');document.getElementById('themeBtn').textContent='☀️'}
let soundOn=true,audioCtx;function toggleSound(){soundOn=!soundOn;document.getElementById('soundBtn').textContent=soundOn?'🔊 صدا روشن است':'🔇 صدا خاموش است';if(soundOn)playTone('#7c3aed')}
function playTone(hex){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=440+parseInt(hex.slice(1,3),16);o.type='sine';g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.035,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.22);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.23)}catch(e){}}
async function shareResult(){const text=`راز رنگ تولد من\n${document.getElementById('date').textContent}\n${document.getElementById('gregDate').innerText}\nرنگ: ${document.getElementById('color').textContent} ${document.getElementById('hex').textContent}\nویژگی: ${document.getElementById('trait').textContent}`;if(navigator.share){try{await navigator.share({title:'راز رنگ تولد',text})}catch(e){}}else{try{await navigator.clipboard.writeText(text);showToast('نتیجه کپی شد ✨')}catch(e){showToast('اشتراک‌گذاری در این مرورگر در دسترس نیست')}}}
async function downloadCard(){const m=Number(monthSelect.value),d=Number(daySelect.value),y=Number(yearSelect.value);if(!m||!d||!y){showToast('اول تاریخ تولدت را کامل کن ✨');return}await document.fonts.ready;const x=getData(m,d),g=jalaliToGregorian(y,m,d),c=document.createElement('canvas');c.width=1200;c.height=1600;const ctx=c.getContext('2d'),grad=ctx.createLinearGradient(0,0,1200,1600);grad.addColorStop(0,x.color);grad.addColorStop(.48,'#ffffff');grad.addColorStop(1,'#eef2ff');ctx.fillStyle=grad;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='rgba(255,255,255,.86)';roundRect(ctx,80,80,1040,1440,55);ctx.textAlign='center';ctx.fillStyle='#101828';ctx.font='900 42px Vazirmatn';ctx.fillText('راز رنگ تولد',600,180);ctx.font='800 58px Vazirmatn';ctx.fillText(`${faDigits(d)} ${months[m-1]} ${faDigits(y)}`,600,290);ctx.font='700 34px Vazirmatn';ctx.fillStyle='#667085';ctx.fillText(`${faDigits(g[2])} ${gregMonths[g[1]-1]} ${faDigits(g[0])}`,600,350);ctx.beginPath();ctx.arc(600,575,170,0,Math.PI*2);ctx.fillStyle=x.color;ctx.shadowColor=x.color;ctx.shadowBlur=55;ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#101828';ctx.font='900 58px Vazirmatn';ctx.fillText(x.colorName,600,850);ctx.font='800 48px Vazirmatn';ctx.fillText(`✦ ${x.trait} ✦`,600,940);ctx.font='700 28px monospace';ctx.fillText(x.color,600,1000);ctx.font='700 28px Vazirmatn';ctx.fillText(`سن: ${faDigits(Math.max(0,ageYears(g)))} سال`,600,1080);ctx.font='600 25px Vazirmatn';ctx.fillStyle='#667085';wrapText(ctx,x.description,600,1170,820,45);ctx.font='600 20px Vazirmatn';ctx.fillText('birthday color experience ✨',600,1400);const a=document.createElement('a');a.download=`birthday-color-${y}-${m}-${d}.jpg`;a.href=c.toDataURL('image/jpeg',.94);a.click();showToast('کارت JPG با تاریخ شمسی و میلادی آماده شد 🖼️')}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function wrapText(ctx,text,x,y,max,lh){const words=text.split(' ');let line='';for(const word of words){const test=line+word+' ';if(ctx.measureText(test).width>max){ctx.fillText(line,x,y);line=word+' ';y+=lh}else line=test}ctx.fillText(line,x,y)}
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}